# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.55.0"
    hooks:
      - id: eslint
        files: \.[jt]sx|js?$  # *.js, *.jsx, *.ts, *.tsx
        types: [ file ]
        additional_dependencies:
          - eslint@8.55.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        files: \.[jt]sx|js|css?$  # *.js, *.jsx, *.ts, *.tsx, *.css
        types: [ file ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.0
    hooks:
      # linter, drop-in replacement for flake8, isort, etc...
      - id: ruff
        # automatically fix some issues
        args: [ --fix ]
      # formatter, drop-in replacement for black
      - id: ruff-format
